### ISSUE TITLE
unneeded delay in momentary layer switch

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#201]
Press Fn(Layer switch momentary) then a key on the layer immediately, you will see delay before appearing the key on terminal.

EDIT: The delay is obvious when keeping the key preessed to get key repeating. For example, users keep 'Fn + ;' pressed down on HHKB keymap to get left arrow repeating. Meanwhile, if the key is released immediately it registered when released and the delay is not obvious.

The delay seems to be related to `TAPPING_TERM`.

Probably tapping code has a bug.

https://geekhack.org/index.php?topic=56494.msg1715297#msg1715297

**Comment by boblehest** [comment]
Hey, I noticed the delay as well some time ago (My LEDs indicate the active layer, so the delay was very apparent), and today it hit me what was causing the delay. It's the tapping delay, as you said, so the issue isn't with the tapping mechanism, but the fact that it's being used wrongly. :p

The fix is rather simple, change this define:

    #define ACTION_LAYER_MOMENTARY(layer)    ACTION_LAYER_ON_OFF(layer)

into:

    #define ACTION_LAYER_MOMENTARY(layer)    ACTION_LAYER_INVERT(layer, ON_BOTH)

**Comment by tmk** [comment]
Nice.

And this gaves me a clue of where the problem root was.

Fixed at 1f4a22ee81ec1986d1ca190c78c66231d37b50e2.
