### ISSUE TITLE
[Help needed] Teensy 3.2 - Keys get inverted while typing

### ISSUE THREAD

**Issue by danielepo** [tmk/tmk_keyboard#582]
Hello!
I'm having an issue with one IBM Model M 122 keyboard that I converted to use USB. 

I rebuild the controller using a Teensy 3.2 and it works almost great, I'm facing an issue where, if you type fast enough, some keys will get swapped but I don't know where to look. 

this is the configuration that I use for the keyboard:

https://github.com/danielepo/ibm.122.Teensy3.2

I suspect is something related to the Teensy 3.2 because I have converted another keyboard (same model) using a Teensy++ 2.0 and so far I don't have this problem.

**Comment by tmk** [comment]
I can come up with two posibilities of the transpose issue by quick thought;
1) Due to slow scan rate two key events cannot be perceived in correct order.
Make sure that `matrix_scan()` is called with short enough interval like a few milli seconds. Try placing `xprintf("%d\n", timer_read());` in the function and use hid_listen tool to see debug print from `xprintf`.

2) Two key events are sent to host with one keyboard report at same time for some reason. TMK sends a key event per report baiscally with LUFA(AVR) while it is not tested thoroughly with ChibiOS(Cortex-M) .
You will have to scan source codes around here perhaps.
https://github.com/tmk/tmk_keyboard/tree/master/tmk_core/protocol/chibios

Let me know  if you find something to be fixed.
