### ISSUE TITLE
ACTION_LAYER_MODS, grave as ESC on Layer 0

### ISSUE THREAD

**Issue by ramonpoca** [tmk/tmk_keyboard#609]
Hi! 
Enjoying a new Alps64, ISO layout.

I want to use GRAVE as ESC on Layer0 (topmost key).
BUT to output grave when RALT+GRAVE.
For the rest of the keys, RALT+key should behave as standard. So I've re-created the standard layout on layer2 and used ACTION_LAYER_MODS(2, RALT) on Layer0's RALT.

Seems to work, except that LAYER2 gets stuck as soon as I press it and doesn't go back to Layer 0.

Did it with the keymap editor: https://goo.gl/3mvgQs

**Comment by tmk** [comment]
Hi,
This layer stuck problem is fixed in source code and your keymap should work with the latest firmware. But alps64 keymap editor has not been updated to the latest yet unfortunately. I'll update it when I got time.

For a while, with old firmware you have to place `TRANS` on the key in Layer 2, instead of RALT.

https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#modifierlayer-stuck
